package mainfiles;


/**
* mainfiles/Hangman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Tuesday, May 1, 2018 6:52:26 PM PHT
*/

public interface Hangman extends HangmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman
